AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A serverless function that listens to incoming webhooks from the Telegram
  Server
Resources:
  Jesus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Jesus/index.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          TABLE_NAME: people
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: PeopleRecords
      Events:
        TelegramServiceAPI:
          Type: Api
          Properties:
            Path: /message
            Method: POST
      CodeUri: s3://jesus-deployement-bucket/39e775b6caeda35db4e3b456b1d3a819
    Metadata:
      SamResourceId: Jesus
  JesusInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - Jesus
        - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Sub: arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*
    Metadata:
      SamResourceId: JesusInvokePermission
  PeopleRecords:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: People
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Metadata:
      SamResourceId: PeopleRecords
